name: chat_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4 
  cloud_firestore: ^6.1.2 
  firebase_storage: ^13.0.6 
  google_sign_in:  ^6.1.5
  intl: ^0.20.2
  google_fonts: ^6.3.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.0
  provider: ^6.1.5+1
  firebase_messaging: ^16.1.1
  dio: ^5.9.1
  googleapis_auth: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.2.1
  flutter_image_compress: ^2.4.0
  cloudinary_public: ^0.23.1
  flutter_dotenv: ^6.0.0
 




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.5	


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  fonts:
    - family: EmojiFont  # Use a clear name
      fonts:
        - asset: assets/fonts/NotoColorEmoji.ttf
  assets:
    - assets/images/
    - .env 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Tea.png"
  adaptive_icon_background: "#7E57C2" 
  adaptive_icon_foreground: "assets/images/Tea.png"

Flutter_native_splash:
  color: "#ffffff"       
  image: assets/logo.png  
 